spring:
  application:
    name: fallback-demo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
hystrix:
  dashboard:
    proxy-stream-allow-list: "*"